# Generated by Django 2.2.7 on 2019-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teenager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_mother', models.CharField(max_length=255)),
                ('name_father', models.CharField(blank=True, max_length=255, null=True)),
                ('date_birth', models.DateField()),
                ('type_sex', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=355, null=True)),
            ],
        ),
    ]
