# Generated by Django 2.2.7 on 2019-12-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenagers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenager',
            name='address',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='teenager',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='teenager',
            name='name_father',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do pai'),
        ),
        migrations.AlterField(
            model_name='teenager',
            name='name_mother',
            field=models.CharField(max_length=255, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='teenager',
            name='notes',
            field=models.CharField(max_length=20, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='teenager',
            name='type_sex',
            field=models.CharField(max_length=20, verbose_name='Sexo'),
        ),
    ]
