# Generated by Django 2.2.7 on 2019-12-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenagers', '0002_auto_20191207_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='teenager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
