# Generated by Django 2.2.7 on 2019-12-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenagers', '0003_teenager_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenager',
            name='date_birth',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='teenager',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
