# Generated by Django 2.2.7 on 2019-12-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teenagers', '0004_auto_20191207_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenager',
            name='notes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='teenager',
            name='type_sex',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo'),
        ),
    ]
